name: CENTURY
channels:
    - defaults
    - conda-forge
dependencies:
    - python=3.6
    - numpy=1.13
    - scipy=1.0
    - sympy=1.1
    - pandas=0.21
    - matplotlib=2.1
    - notebook=5.2
    - jupyter=1.0
    - seaborn=0.8
    - widgetsnbextension=3.0
